/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-10-27 15:45:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.applicant_002dform;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class applicant_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"/jquery/jquery-1.11.3.js\"></script>\r\n");
      out.write("<link href=\"/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/dark-theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/form-elements.css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>77 Soft Applicant App</title>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\tCONTEXT: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top inverse-dark\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\taria-controls=\"navbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">77 Soft Applicant App</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-left\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<!-- \t\t\t<div class=\"col-sm-3 col-md-2 sidebar\"> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t<ul class=\"nav nav-sidebar\"> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li><a href=\"#\">Primary Information</a></li> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li><a href=\"#otherInformation\">Other Information</a></li> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li><a href=\"#prevEmployment\">Current/Previous Employment -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t\t\t\tInformation</a></li> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li><a href=\"#appInformation\">Application Information</a></li> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t</div> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\"> -->\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/insertApplicant\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t<!-- -----------------------------FIRST SECTION--------------------------- -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"primaryInformation\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Primary Information</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"well welldark-sm\">\r\n");
      out.write("\t\t\t\t\t\t<strong><span class=\"glyphicon glyphicon-asterisk\"></span>Required\r\n");
      out.write("\t\t\t\t\t\t\tField</strong>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"firstName\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">First Name</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"firstName\" name=\"firstName\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"First Name\" required> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"lastName\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Last Name</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"lastName\" name=\"lastName\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Last Name\" required> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"middleName\" class=\"col-sm-2 control-label\">Middle\r\n");
      out.write("\t\t\t\t\t\t\tName</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"middleName\" name=\"middleName\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Middle Name\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"birthDate\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Date of\r\n");
      out.write("\t\t\t\t\t\t\tBirth</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"birthDate\" name=\"birthdate\" placeholder=\"Date of Birth\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" type=\"text\" onfocus=\"(this.type='date')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"(this.type='text')\" required> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"civilStatus\" class=\"col-sm-2 control-label\">Civil\r\n");
      out.write("\t\t\t\t\t\t\tStatus</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"civilStatus\" name=\"civilStatus\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled selected>Civil Status</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"single\">Single</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"married\">Married</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"widowed\">Widowed</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"separated\">Separated</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"gender\" class=\"col-sm-2 control-label\">Gender</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"gender\" name=\"gender\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled selected>Gender</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"male\">Male</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"female\">Female</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"presentAddress\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Present\r\n");
      out.write("\t\t\t\t\t\t\tAddress</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea id=\"presentAddress\" name=\"presentAddress\" class=\"form-control\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcols=\"50\" placeholder=\"Present Address\" required></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"permanentAddress\" class=\"col-sm-2 control-label\">Permanent\r\n");
      out.write("\t\t\t\t\t\t\tAddress</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"permanentAddress\" name=\"permanentAddress\" class=\"form-control\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcols=\"50\" placeholder=\"Permanent Address\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"email\" class=\"col-sm-2 control-label required-label\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"email\" name=\"emailAddress\" class=\"form-control\" type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Email Address\" required /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"mobile\" class=\"col-sm-2 control-label required-label\">Mobile\r\n");
      out.write("\t\t\t\t\t\t\tNumber</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"tel\" name=\"mobileNumber\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Mobile Number\" required> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"phone\" class=\"col-sm-2 control-label\">Telephone\r\n");
      out.write("\t\t\t\t\t\t\tNumber</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"tel\" name=\"telephoneNumber\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Telephone Number\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"citizenship\" class=\"col-sm-2 control-label\">Citizenship</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"citizenship\" name=\"citizenship\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Citizenship\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- ------------------------------------------ SECOND SECTION ---------------------- -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"otherInformation\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Other Information</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"education\" class=\"col-sm-2 control-label\">Educational\r\n");
      out.write("\t\t\t\t\t\t\tAttainment</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"education\" name=\"educationAttainments\" class=\"form-control\" rows=\"5\" cols=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Educational Attainment\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"achievements\" class=\"col-sm-2 control-label\">Achievements\r\n");
      out.write("\t\t\t\t\t\t\t/ Certifications</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"achievements\" name=\"achievementsCertifications\" class=\"form-control\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcols=\"50\" placeholder=\"Achievements/Certifications\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"skills\" class=\"col-sm-2 control-label\">Skills</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"skills\" name=\"skills\" class=\"form-control\" rows=\"5\" cols=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Skills\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- ---------------------------------------- THIRD SECTION ----------------------------- -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"prevEmployment\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Current/Previous Employment Information</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"company\" class=\"col-sm-2 control-label\">Company</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"company\" name=\"currentPreviousCompany\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Company\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"dateStart\" class=\"col-sm-2 control-label\">Date\r\n");
      out.write("\t\t\t\t\t\t\tStarted</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"dateStart\" name=\"currentPreviousDateStarted\" placeholder=\"Date Started\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" type=\"text\" onfocus=\"(this.type='date')\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonblur=\"(this.type='text')\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"dateEnd\" class=\"col-sm-2 control-label\">Date\r\n");
      out.write("\t\t\t\t\t\t\tEnded</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"dateEnd\" name=\"currentPreviousDateEnded\" placeholder=\"Date Ended\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" onfocus=\"(this.type='date')\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonblur=\"(this.type='text')\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"position\" class=\"col-sm-2 control-label\">Position</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"position\" name=\"currentPreviousPosition\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Position\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"manager\" class=\"col-sm-2 control-label\">Manager\r\n");
      out.write("\t\t\t\t\t\t\tName</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"manager\" name=\"currentPreviousManager\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Manager Name\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- ---------------------------------------------------- FOURTH SECTION ---------------------------- -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"appInformation\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Application Information</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"positionApplied\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Position\r\n");
      out.write("\t\t\t\t\t\t\tApplying For</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"positionApplied\" name=\"positionApplyingFor\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Position\" required> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"availability\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Availability\r\n");
      out.write("\t\t\t\t\t\t\tof Employment</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"availability\" name=\"availabilityOfEmployment\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Availability of Employment\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" onfocus=\"(this.type='date')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"(this.type='text')\" required> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"uploadResume\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Additional Attachments</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"resume\" class=\"col-sm-2 control-label\">Resume</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"resume\" name=\"resume\" type=\"file\" class=\"form-control\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"custom\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"reset\" class=\"btncustom\">Clear Fields</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btncustom\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("\t<script src=\"/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
