/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-10-28 02:50:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.applicant_002dform;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class applicant_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("<script src=\"/jquery/jquery-1.11.3.js\"></script>\n");
      out.write("<script src=\"/js/bootstrap.min.js\"></script>\n");
      out.write("<link href=\"/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/dark-theme.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/form-elements.css\" />\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Seven Seven GSI | Applicant Form</title>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top inverse-dark\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\"\n");
      out.write("\t\t\t\t\taria-controls=\"navbar\">\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> \n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> \n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> \n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"../index.html\"><img src=\"../img/77logo-black.png\" class=\"img-responsive\" width=\"120px\"/></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-left\">\n");
      out.write("\t\t\t\t\t<li><a href=\"../index.html\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"../applicant-form/applicant.jsp\">Applicant Form</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"../leave-management/leave.jsp\">Leave Management</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<div class=\"page-start container-fluid\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<!-- \t\t\t<div class=\"col-sm-3 col-md-2 sidebar\"> -->\n");
      out.write("\t\t\t<!-- \t\t\t\t<ul class=\"nav nav-sidebar\"> -->\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li><a href=\"#\">Primary Information</a></li> -->\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li><a href=\"#otherInformation\">Other Information</a></li> -->\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li><a href=\"#prevEmployment\">Current/Previous Employment -->\n");
      out.write("\t\t\t<!-- \t\t\t\t\t\t\tInformation</a></li> -->\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li><a href=\"#appInformation\">Application Information</a></li> -->\n");
      out.write("\t\t\t<!-- \t\t\t\t</ul> -->\n");
      out.write("\t\t\t<!-- \t\t\t</div> -->\n");
      out.write("\t\t\t<!-- \t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\"> -->\n");
      out.write("\t\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" action=\"/applicant-form/insertApplicant\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("\t\t\t\t\t<!-- -----------------------------FIRST SECTION--------------------------- -->\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"primaryInformation\">\n");
      out.write("\t\t\t\t\t\t<h2>Primary Information</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"well welldark-sm\">\n");
      out.write("\t\t\t\t\t\t<strong>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-asterisk\"></span>\n");
      out.write("\t\t\t\t\t\t\tRequired Field\n");
      out.write("\t\t\t\t\t\t</strong>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"firstName\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">First Name</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"firstName\" name=\"firstName\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"First Name\" required> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"lastName\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Last Name</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"lastName\" name=\"lastName\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Last Name\" required> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"middleName\" class=\"col-sm-2 control-label\">Middle\n");
      out.write("\t\t\t\t\t\t\tName</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"middleName\" name=\"middleName\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Middle Name\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"birthDate\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Date of\n");
      out.write("\t\t\t\t\t\t\tBirth</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"birthDate\" name=\"birthdate\" placeholder=\"Date of Birth\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" type=\"text\" onfocus=\"(this.type='date')\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"(this.type='text')\" required> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"civilStatus\" class=\"col-sm-2 control-label\">Civil\n");
      out.write("\t\t\t\t\t\t\tStatus</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<select id=\"civilStatus\" name=\"civilStatus\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled selected>Civil Status</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"single\">Single</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"married\">Married</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"widowed\">Widowed</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"separated\">Separated</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"gender\" class=\"col-sm-2 control-label\">Gender</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<select id=\"gender\" name=\"gender\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled selected>Gender</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"male\">Male</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"female\">Female</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"presentAddress\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Present\n");
      out.write("\t\t\t\t\t\t\tAddress</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<textarea id=\"presentAddress\" name=\"presentAddress\" class=\"form-control\" rows=\"5\"\n");
      out.write("\t\t\t\t\t\t\t\t\tcols=\"50\" placeholder=\"Present Address\" required></textarea>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"permanentAddress\" class=\"col-sm-2 control-label\">Permanent\n");
      out.write("\t\t\t\t\t\t\tAddress</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"permanentAddress\" name=\"permanentAddress\" class=\"form-control\" rows=\"5\"\n");
      out.write("\t\t\t\t\t\t\t\tcols=\"50\" placeholder=\"Permanent Address\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"email\" class=\"col-sm-2 control-label required-label\">Email</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"email\" name=\"emailAddress\" class=\"form-control\" type=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Email Address\" required /> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"mobile\" class=\"col-sm-2 control-label required-label\">Mobile\n");
      out.write("\t\t\t\t\t\t\tNumber</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"tel\" name=\"mobileNumber\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Mobile Number\" required> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"phone\" class=\"col-sm-2 control-label\">Telephone\n");
      out.write("\t\t\t\t\t\t\tNumber</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"tel\" name=\"telephoneNumber\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Telephone Number\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"citizenship\" class=\"col-sm-2 control-label\">Citizenship</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"citizenship\" name=\"citizenship\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Citizenship\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- ------------------------------------------ SECOND SECTION ---------------------- -->\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"otherInformation\">\n");
      out.write("\t\t\t\t\t\t<h2>Other Information</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"education\" class=\"col-sm-2 control-label\">Educational\n");
      out.write("\t\t\t\t\t\t\tAttainment</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"education\" name=\"educationAttainments\" class=\"form-control\" rows=\"5\" cols=\"50\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Educational Attainment\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"achievements\" class=\"col-sm-2 control-label\">Achievements\n");
      out.write("\t\t\t\t\t\t\t/ Certifications</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"achievements\" name=\"achievementsCertifications\" class=\"form-control\" rows=\"5\"\n");
      out.write("\t\t\t\t\t\t\t\tcols=\"50\" placeholder=\"Achievements/Certifications\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"skills\" class=\"col-sm-2 control-label\">Skills</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"skills\" name=\"skills\" class=\"form-control\" rows=\"5\" cols=\"50\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Skills\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- ---------------------------------------- THIRD SECTION ----------------------------- -->\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"prevEmployment\">\n");
      out.write("\t\t\t\t\t\t<h2>Current/Previous Employment Information</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"company\" class=\"col-sm-2 control-label\">Company</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"company\" name=\"currentPreviousCompany\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Company\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"dateStart\" class=\"col-sm-2 control-label\">Date\n");
      out.write("\t\t\t\t\t\t\tStarted</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"dateStart\" name=\"currentPreviousDateStarted\" placeholder=\"Date Started\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" type=\"text\" onfocus=\"(this.type='date')\"\n");
      out.write("\t\t\t\t\t\t\t\tonblur=\"(this.type='text')\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"dateEnd\" class=\"col-sm-2 control-label\">Date\n");
      out.write("\t\t\t\t\t\t\tEnded</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"dateEnd\" name=\"currentPreviousDateEnded\" placeholder=\"Date Ended\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" onfocus=\"(this.type='date')\"\n");
      out.write("\t\t\t\t\t\t\t\tonblur=\"(this.type='text')\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"position\" class=\"col-sm-2 control-label\">Position</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"position\" name=\"currentPreviousPosition\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Position\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"manager\" class=\"col-sm-2 control-label\">Manager\n");
      out.write("\t\t\t\t\t\t\tName</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"manager\" name=\"currentPreviousManager\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Manager Name\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- ---------------------------------------------------- FOURTH SECTION ---------------------------- -->\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"appInformation\">\n");
      out.write("\t\t\t\t\t\t<h2>Application Information</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"positionApplied\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Position\n");
      out.write("\t\t\t\t\t\t\tApplying For</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"positionApplied\" name=\"positionApplyingFor\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Position\" required> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"availability\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-sm-2 control-label required-label\">Availability\n");
      out.write("\t\t\t\t\t\t\tof Employment</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"availability\" name=\"availabilityOfEmployment\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Availability of Employment\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" onfocus=\"(this.type='date')\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"(this.type='text')\" required> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-asterisk\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group title\" id=\"uploadResume\">\n");
      out.write("\t\t\t\t\t\t<h2>Additional Attachments</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"resume\" class=\"col-sm-2 control-label\">Resume</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"resume\" name=\"resume\" type=\"file\" class=\"form-control\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"custom\">\n");
      out.write("\t\t\t\t\t\t\t<button type=\"reset\" class=\"btncustom\">Clear</button>\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btncustom\">Submit</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
